version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - ingest.geoip.downloader.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
      - xpack.security.enabled=true
    networks:
      - es-net
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - ./esdata:/usr/share/elasticsearch/data
  logstash:
    container_name: es-logstash
    build: 
      context: ./elastic-search/
      dockerfile: ./Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    networks:
      - es-net
    ports:
      - "5002:5000"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.2.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge